import React, { useRef, useState } from 'react';
import { Alert, FlatList, Image, KeyboardAvoidingView, Linking, Platform, Pressable, Text, TextInput, View } from 'react-native';
import { normalizeName, Trip } from '../trips/tripModel';
import { Conversation, Friend, Message } from './chatModel';
import { Avatar, useChatUi, Icon, IconButton,  Sheet, } from './chatUi';
import { Button } from '../trips/tripUi';
export default function ConversationScreen({ conversation, friends, user, trips, onPin, trip, onBack, onSend, onInvite, onTrip }: { conversation: Conversation; friends: Friend[]; user: { displayName: string; email: string }; trips: Trip[]; onPin: (id?: string) => void; trip?: Trip; onBack: () => void; onSend: (text: string) => void; onInvite: (id: string) => void; onTrip: (id: string) => void }) {
  const { c, s, u } = useChatUi();
  const [input, setInput] = useState('');
  const [invite, setInvite] = useState(false);
  const [pin, setPin] = useState(false);
  const [pinQuery, setPinQuery] = useState('');
  const [inviteQuery, setInviteQuery] = useState('');
  const [person, setPerson] = useState<{ name: string; detail?: string } | null>(null);
  const [location, setLocation] = useState(false);
  const [coordinates, setCoordinates] = useState('');
  const [error, setError] = useState('');
  const list = useRef<FlatList<Message>>(null);
  const group = conversation.type === 'group';
  const send = () => { if (!input.trim()) return; onSend(input); setInput(''); };
  const unavailable = () => Alert.alert('Chưa hỗ trợ cuộc gọi', 'Tính năng gọi thoại và video sẽ được bổ sung sau.');
  const sendLocation = () => {
    const parts = coordinates.split(',').map(value => value.trim());
    const [lat, lng] = parts.map(Number);
    if (parts.length !== 2 || parts.some(part => !part) || !Number.isFinite(lat) || !Number.isFinite(lng) || Math.abs(lat) > 90 || Math.abs(lng) > 180) return setError('Nhập vĩ độ, kinh độ hợp lệ, ví dụ: 11.9404, 108.4583.');
    onSend(`Vị trí: https://www.openstreetmap.org/?mlat=${lat}&mlon=${lng}#map=16/${lat}/${lng}`); setLocation(false); setCoordinates('');
  };
  return <KeyboardAvoidingView style={[u.screen, { backgroundColor: c.pale }]} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>
    <View style={[s.header, { paddingHorizontal: 12, gap: 8 }]}><IconButton name="arrow-left" label="Quay lại" onPress={onBack} /><Pressable accessibilityRole="button" onPress={() => { if (group) setInvite(true); else { const friend = friends.find(item => conversation.members.includes(item.id)); setPerson({ name: friend?.name ?? conversation.name, detail: friend?.phone }); } }} style={s.grow}><Text numberOfLines={1} style={s.title}>{conversation.name}</Text><Text style={s.small}>{group ? `${conversation.members.length + 1} thành viên · Đồng hành` : 'Tin nhắn'}</Text></Pressable>{group ? <IconButton name="account-plus-outline" label="Mời bạn vào nhóm" onPress={() => setInvite(true)} /> : <><IconButton name="phone-outline" label="Gọi thoại" onPress={unavailable} /><IconButton name="video-outline" label="Gọi video" onPress={unavailable} /></>}</View>
    {trip ? <View style={[s.row, { paddingHorizontal: 12, backgroundColor: c.white, borderBottomWidth: 1, borderColor: c.border, gap: 4 }]}><Pressable accessibilityRole="button" style={[s.row, s.grow, { minHeight: 64, gap: 8 }]} onPress={() => onTrip(trip.id)}><View style={{ width: 32, height: 32, borderRadius: 8, backgroundColor: c.primaryLight, alignItems: 'center', justifyContent: 'center' }}><Icon name="pin-outline" size={16} /></View><View style={s.grow}><Text numberOfLines={1} style={[s.text, { fontWeight: '600' }]}>{trip.title}</Text><Text style={s.small}>Đã ghim · {trip.dayPlans.length} ngày · {trip.dayPlans.flatMap(day => day.stops).length} địa điểm</Text></View><Icon name="chevron-right" size={16} color={c.muted} /></Pressable><Pressable accessibilityLabel="Đổi lịch trình ghim" onPress={() => { setPinQuery(''); setPin(true); }} style={{ width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }}><Icon name="refresh" size={16} /></Pressable><Pressable accessibilityLabel="Bỏ ghim lịch trình" onPress={() => onPin(undefined)} style={{ width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }}><Icon name="pin-off-outline" size={16} color={c.muted} /></Pressable></View> : <Pressable accessibilityLabel="Chọn lịch trình ghim" onPress={() => { setPinQuery(''); setPin(true); }} style={[s.row, { paddingHorizontal: 16, minHeight: 44, backgroundColor: c.white, borderBottomWidth: 1, borderColor: c.border }]}><Icon name="pin-outline" size={16} /><Text style={[s.link, s.grow]}>Ghim lịch trình</Text><Icon name="plus" size={16} /></Pressable>}
    <FlatList ref={list} data={conversation.messages} keyExtractor={item => item.id} contentContainerStyle={{ padding: 16, gap: 12, flexGrow: 1 }} onContentSizeChange={() => list.current?.scrollToEnd({ animated: false })} keyboardShouldPersistTaps="handled" ListEmptyComponent={<View style={u.empty}><Text style={s.small}>Bắt đầu cuộc trò chuyện với {conversation.name}</Text></View>} renderItem={({ item }) => <View style={{ flexDirection: 'row', justifyContent: item.isMe ? 'flex-end' : 'flex-start', alignItems: 'flex-end', gap: 8 }}>{!item.isMe && <Pressable accessibilityRole="button" accessibilityLabel={item.isMe ? user.displayName : item.senderName} onPress={() => { const friend = friends.find(value => value.name === item.senderName); setPerson(item.isMe ? { name: user.displayName, detail: user.email } : { name: friend?.name ?? item.senderName, detail: friend?.phone }); }}><Avatar size={32} text={(item.isMe ? user.displayName : item.senderName).slice(0, 2).toUpperCase()} /></Pressable>}<View style={{ maxWidth: '78%', gap: 3 }}>{group && !item.isMe && <Text style={s.small}>{item.senderName}</Text>}<View style={{ padding: 12, borderRadius: 18, backgroundColor: item.isMe ? c.blue : c.white, borderWidth: item.isMe ? 0 : 1, borderColor: c.border }}><Text selectable style={{ color: item.isMe ? c.onBlue : c.ink, fontSize: 14, lineHeight: 20 }}>{item.text}</Text>{item.text.includes('https://www.openstreetmap.org/') && <Pressable accessibilityRole="link" onPress={() => { const url = item.text.match(/https:\/\/www\.openstreetmap\.org\/\S+/)?.[0]; if (url) void Linking.openURL(url).catch(() => Alert.alert('Không mở được bản đồ')); }}><Text style={{ color: item.isMe ? c.onBlue : c.blue, textDecorationLine: 'underline', paddingVertical: 8 }}>Mở bản đồ</Text></Pressable>}<Text style={{ textAlign: 'right', marginTop: 4, fontSize: 12, color: item.isMe ? '#ffffffcc' : c.muted }}>{item.time}</Text></View></View></View>} />
    <View style={[s.footer, s.row, { padding: 12 }]}>{!group && <IconButton name="map-marker-outline" label="Gửi tọa độ vị trí" onPress={() => { setError(''); setLocation(true); }} />}<TextInput value={input} onChangeText={setInput} accessibilityLabel="Nhập tin nhắn" placeholder={group ? 'Nhắn tin cho cả nhóm...' : 'Nhập tin nhắn...'} placeholderTextColor={c.muted} style={[s.input, s.grow, { borderRadius: 24, maxHeight: 100, fontSize: 16 }]} multiline maxLength={4000} /><IconButton name="send-outline" label="Gửi tin nhắn" blue disabled={!input.trim()} onPress={send} /></View>
    <Sheet visible={pin} title="Ghim lịch trình" onClose={() => setPin(false)}><Text style={s.text}>Chọn một chuyến đi của bạn để ghim vào cuộc trò chuyện này.</Text><View style={u.search}><Icon name="magnify" size={16} color={c.muted} /><TextInput value={pinQuery} onChangeText={setPinQuery} accessibilityLabel="Tìm lịch trình để ghim" placeholder="Tìm tên chuyến đi hoặc điểm đến" placeholderTextColor={c.muted} style={u.searchInput} /></View>{!trips.length && <Text style={s.text}>Bạn chưa có chuyến đi. Hãy tạo và lưu chuyến đi trước khi ghim.</Text>}{trips.filter(item => normalizeName(`${item.title} ${item.city}`).includes(normalizeName(pinQuery))).map(item => <Pressable key={item.id} accessibilityRole="button" onPress={() => { onPin(item.id); setPin(false); }} style={[s.row, { minHeight: 80, borderBottomWidth: 1, borderColor: c.pale }]}>{item.image ? <Image source={{ uri: item.image }} style={{ width: 48, height: 56, borderRadius: 8 }} /> : <View style={{ width: 48, height: 56, borderRadius: 8, backgroundColor: c.pale, alignItems: 'center', justifyContent: 'center' }}><Icon name="pin-outline" /></View>}<View style={s.grow}><Text style={[s.text, { fontWeight: '600' }]}>{item.title}</Text><Text style={s.small}>{item.dayPlans.length} ngày · {item.dayPlans.flatMap(day => day.stops).length} địa điểm</Text></View><Icon name={item.id === trip?.id ? 'check' : 'pin-outline'} size={18} color={item.id === trip?.id ? c.blue : c.muted} /></Pressable>)}</Sheet>
    <Sheet visible={!!person} title="Thông tin cá nhân" onClose={() => setPerson(null)}><View style={{ alignItems: 'center', paddingVertical: 20, gap: 12 }}><Avatar size={80} text={person?.name.slice(0, 2).toUpperCase() ?? ''} /><Text style={[s.title, { fontSize: 21 }]}>{person?.name}</Text>{!!person?.detail && <Text style={s.text}>{person.detail}</Text>}</View><View style={[s.card, { borderWidth: 1, borderColor: c.border }]}><Text style={s.title}>Giới thiệu</Text><Text style={s.text}>Chưa có thông tin giới thiệu.</Text></View><Button label="Nhắn tin" onPress={() => setPerson(null)} /></Sheet>
    <Sheet visible={invite} title="Mời bạn bè vào nhóm" onClose={() => setInvite(false)}><View style={s.row}><View style={{ width: 44, height: 44, borderRadius: 22, backgroundColor: c.primaryLight, alignItems: 'center', justifyContent: 'center' }}><Icon name="account-group-outline" /></View><View><Text style={s.title}>Thêm bạn đồng hành</Text><Text style={s.small}>{conversation.name}</Text></View></View><View style={u.search}><Icon name="magnify" size={16} color={c.muted} /><TextInput value={inviteQuery} onChangeText={setInviteQuery} accessibilityLabel="Tìm bạn để mời" placeholder="Tìm tên hoặc số điện thoại" style={[u.searchInput, { fontSize: 16 }]} /></View>{!friends.length && <Text style={s.text}>Chưa có bạn bè để mời.</Text>}{friends.filter(friend => normalizeName(`${friend.name} ${friend.phone}`).includes(normalizeName(inviteQuery))).map(friend => { const added = conversation.members.includes(friend.id); return <View key={friend.id} style={[s.row, { padding: 12, borderRadius: 11, borderWidth: 1, borderColor: c.border }]}><Pressable onPress={() => { setInvite(false); setPerson({ name: friend.name, detail: friend.phone }); }}><Avatar text={friend.avatar} /></Pressable><View style={s.grow}><Text style={s.title}>{friend.name}</Text><Text style={s.small}>{friend.phone}</Text></View><Button label={added ? 'Đã thêm' : 'Mời'} disabled={added} onPress={() => onInvite(friend.id)} /></View>; })}</Sheet>
    <Sheet visible={location} title="Chia sẻ vị trí trên OpenStreetMap" onClose={() => setLocation(false)}><Text style={s.small}>Nhập tọa độ muốn chia sẻ. Đây không phải vị trí GPS tự động.</Text><TextInput accessibilityLabel="Vĩ độ, kinh độ" value={coordinates} onChangeText={setCoordinates} placeholder="11.9404, 108.4583" style={s.input} />{!!error && <Text style={s.error}>{error}</Text>}<Button label="Gửi vị trí" onPress={sendLocation} /></Sheet>
  </KeyboardAvoidingView>;
}
