import React, { useState } from 'react';
import { ImageBackground, Pressable, ScrollView, Text, View } from 'react-native';
import { displayDate, durationLabel, Trip, TripStatus, tripStops } from './tripModel';
import { Icon, useTripUi } from './tripUi';
export default function ManageTripsScreen({ trips, onTrack }: { trips: Trip[]; onTrack: (id: string) => void }) {
  const { c, s } = useTripUi();
  const [segment, setSegment] = useState<TripStatus>('upcoming');
  const segments = [{ key: 'upcoming', label: 'Sắp tới' }, { key: 'completed', label: 'Đã đi' }, ...(trips.some(trip => trip.status === 'cancelled') ? [{ key: 'cancelled', label: 'Đã hủy' }] : [])];
  const filtered = trips.filter(trip => trip.status === segment);
  return <View style={s.screen}>
    <View style={{ backgroundColor: c.chrome, paddingHorizontal: 16, paddingVertical: 12 }}><Text style={{ color: c.ink, fontSize: 20, fontWeight: '600', lineHeight: 26, minHeight: 44, textAlignVertical: 'center' }}>Chuyến đi</Text><Text style={{ color: c.muted, fontSize: 14, lineHeight: 20, marginTop: 4 }}>Những hành trình đang chờ bạn.</Text></View>
    <View style={{ flexDirection: 'row', gap: 12, paddingHorizontal: 16, paddingBottom: 12, backgroundColor: c.chrome }}>{segments.map(item => <Pressable key={item.key} accessibilityRole="tab" accessibilityState={{ selected: segment === item.key }} onPress={() => setSegment(item.key as TripStatus)} style={{ flex: 1, minHeight: 44, borderWidth: 1, borderColor: segment === item.key ? `${c.blue}66` : c.border, backgroundColor: segment === item.key ? c.primaryLight : 'transparent', borderRadius: 24, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: segment === item.key ? c.blue : c.muted, fontSize: 14, fontWeight: '600' }}>{item.label}</Text></Pressable>)}</View>
    <ScrollView contentContainerStyle={s.body} showsVerticalScrollIndicator={false}>{!filtered.length ? <View style={[s.card, { padding: 24, alignItems: 'center', gap: 16 }]}><Icon name="calendar-month-outline" size={32} /><Text style={[s.title, { fontSize: 20 }]}>Chưa có chuyến đi nào</Text><Text style={{ color: c.muted, fontSize: 14, textAlign: 'center', lineHeight: 20 }}>Nhấn dấu + ở thanh điều hướng bên dưới để tạo chuyến đi mới.</Text></View> : filtered.map(trip => <Pressable key={trip.id} onPress={() => onTrack(trip.id)} style={({ pressed }) => [{ backgroundColor: c.white, borderRadius: 18, overflow: 'hidden' }, pressed && { opacity: 0.88, transform: [{ scale: 0.98 }] }]}>
      <ImageBackground source={{ uri: trip.image ?? 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80' }} style={{ height: 176, backgroundColor: c.pale }}><Text style={{ position: 'absolute', top: 12, right: 12, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 24, backgroundColor: c.white, color: c.ink, fontSize: 12, fontWeight: '600' }}>{durationLabel(trip.dayPlans.length)}</Text></ImageBackground>
      <View style={{ padding: 16, gap: 12 }}><View style={s.row}><Icon name="map-marker-outline" size={14} /><Text style={{ color: c.blue, fontSize: 12 }}>{trip.city || trip.destination}</Text></View><View style={[s.row, { alignItems: 'flex-start' }]}><Text style={[s.grow, { fontSize: 18, lineHeight: 24, fontWeight: '600', color: c.ink }]}>{trip.title}</Text><Icon name="chevron-right" size={20} color={c.muted} /></View><Text style={{ fontSize: 14, color: c.muted }}>{trip.dateMode === 'flexible' ? 'Ngày khởi hành linh hoạt' : `${displayDate(trip.startDate)} – ${displayDate(trip.endDate)}`}</Text><View style={[s.row, { gap: 16, flexWrap: 'wrap' }]}><View style={s.row}><Icon name="navigation-variant-outline" size={14} color={c.muted} /><Text style={s.small}>{tripStops(trip).length} điểm đến</Text></View><View style={s.row}><Icon name="account-group-outline" size={14} color={c.muted} /><Text style={s.small}>{trip.members.length ? `${trip.members.length} bạn đồng hành` : 'Chuyến đi cá nhân'}</Text></View></View></View>
    </Pressable>)}</ScrollView>
  </View>;
}
