import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { addStop, displayDate, moveStop, reorderStop, Trip, TripDestination } from './tripModel';
import { Button, Icon, useTripUi } from './tripUi';
import { useTripPlanViewModel } from './useTripPlanViewModel';
import TripMap from './TripMap';
import PlacePicker from './PlacePicker';
import { Sheet } from '../chat/chatUi';

export default function ManualPlannerScreen({ trip, destination, onBack, onClose, onUpdate, onSave, error }: { trip: Trip; destination: TripDestination; onBack: () => void; onClose: () => void; onUpdate: (trip: Trip) => void; onSave: (trip: Trip) => void; error?: string }) {
  const { c, s } = useTripUi();
  const vm = useTripPlanViewModel({ trip, destination, onBack, onUpdate, onSave, error, initialTab: 0 });
  const [moveId, setMoveId] = useState<string | null>(null);
  const day = Math.max(0, Math.min(vm.tab, trip.dayPlans.length - 1));
  const stops = trip.dayPlans[day].stops;
  const remove = (id: string) => { onUpdate({ ...trip, dayPlans: trip.dayPlans.map(plan => ({ ...plan, stops: plan.stops.filter(stop => stop.id !== id) })) }); vm.setEdit(null); };
  return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>
    <View style={{ height: 56, backgroundColor: c.white, borderBottomWidth: 1, borderColor: c.border, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><Pressable accessibilityLabel="Quay lại cách lên lịch" onPress={onBack} style={{ width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }}><Icon name="arrow-left" size={20} /></Pressable><Text style={s.title}>Tự lên lịch</Text><Pressable accessibilityLabel="Đóng tạo chuyến đi" onPress={onClose} style={{ width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }}><Icon name="close" size={20} /></Pressable></View>
    <ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} stickyHeaderIndices={[2]}>
      <View style={{ backgroundColor: c.white, paddingHorizontal: 16, paddingTop: 16, paddingBottom: 12, gap: 8 }}><TextInput accessibilityLabel="Tên chuyến đi" maxLength={100} value={trip.title} onChangeText={title => onUpdate({ ...trip, title })} style={{ color: c.ink, fontSize: 20, fontWeight: '600', padding: 0 }} /><View style={s.row}><Icon name="map-marker-outline" size={16} color={c.muted} /><Text style={[s.grow, { fontSize: 14, color: c.muted }]}>{destination.fullName || destination.name}</Text></View><View style={s.row}><Icon name="calendar-month-outline" size={16} color={c.muted} /><Text style={s.small}>{trip.dateMode === 'flexible' ? `${trip.dayPlans.length} ngày · Ngày đi linh hoạt` : `${displayDate(trip.startDate)} — ${displayDate(trip.endDate)}`}</Text></View></View>
      <TripMap coords={trip.coords} stops={stops} height={176} rounded={false} label={stops.length ? `${stops.length} điểm dừng` : 'Chọn điểm dừng đầu tiên'} />
      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ flexGrow: 0, backgroundColor: c.white, borderBottomWidth: 1, borderColor: c.border }} contentContainerStyle={{ paddingHorizontal: 16, paddingVertical: 12, gap: 8 }}>{trip.dayPlans.map((plan, index) => <Pressable key={plan.dayNumber} accessibilityRole="tab" accessibilityState={{ selected: day === index }} onPress={() => { vm.setTab(index); vm.setEdit(null); }} style={{ minHeight: 44, borderRadius: 24, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: day === index ? c.avatar : c.pale }}><Text style={{ fontSize: 14, fontWeight: '600', color: day === index ? c.onBlue : c.muted }}>Ngày {index + 1}</Text><Text style={{ fontSize: 12, color: day === index ? '#ffffffcc' : c.muted }}>{plan.stops.length}</Text></Pressable>)}</ScrollView>
      <View style={{ padding: 16, gap: 12, minHeight: 224 }}><View style={s.between}><View style={s.grow}><Text style={[s.title, { fontSize: 21 }]}>Lịch trình ngày {day + 1}</Text><Text style={[s.small, { marginTop: 4 }]}>{trip.dateMode === 'flexible' ? 'Tự chọn giờ và thứ tự các điểm dừng' : destination.name}</Text></View><Pressable accessibilityLabel={`Thêm địa điểm vào ngày ${day + 1}`} onPress={() => vm.setPicker(day)} style={[s.back, { width: 44, height: 44, backgroundColor: c.white, borderWidth: 0 }]}><Icon name="plus" size={20} /></Pressable></View>
        {!stops.length && <View style={[s.card, { paddingHorizontal: 20, paddingVertical: 24, alignItems: 'center' }]}><View style={{ width: 48, height: 48, borderRadius: 24, backgroundColor: c.pale, justifyContent: 'center', alignItems: 'center' }}><Icon name="map-marker-path" size={24} /></View><Text style={s.title}>Một ngày, theo cách của bạn</Text><Text style={{ color: c.muted, fontSize: 14, lineHeight: 20, textAlign: 'center' }}>Thêm nơi muốn ghé, chọn giờ đến và sắp xếp hành trình theo ý bạn.</Text><Button label="Thêm địa điểm đầu tiên" onPress={() => vm.setPicker(day)} /></View>}
        {stops.map((stop, index) => <View key={stop.id} style={{ paddingLeft: 36 }}>
          {index < stops.length - 1 && <View style={{ position: 'absolute', left: 14, top: 28, bottom: -12, width: 1, backgroundColor: c.border }} />}
          <View style={{ position: 'absolute', top: 16, left: 0, width: 28, height: 28, borderRadius: 14, backgroundColor: c.blue, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: c.onBlue, fontSize: 12, fontWeight: '600' }}>{index + 1}</Text></View>
          <View style={[s.card, { padding: 12 }]}><View style={[s.row, { alignItems: 'flex-start' }]}><View style={s.grow}><Text style={s.title}>{stop.name}</Text><View style={[s.row, { marginTop: 8 }]}><Icon name="clock-outline" size={14} /><TextInput accessibilityLabel={`Giờ đến ${stop.name}`} value={stop.time} onChangeText={time => vm.updateStop(stop.id, { time })} maxLength={5} style={{ color: c.blue, fontSize: 12, minHeight: 32, minWidth: 70, padding: 0 }} /></View></View><Pressable accessibilityLabel={`Chỉnh sửa ${stop.name}`} accessibilityState={{ expanded: vm.edit === stop.id }} onPress={() => vm.setEdit(vm.edit === stop.id ? null : stop.id)} style={{ width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }}><Icon name="dots-horizontal" size={20} color={c.muted} /></Pressable></View>
            {vm.edit === stop.id ? <View style={[s.divider, { gap: 12 }]}><Text style={s.small}>Ghi chú</Text><TextInput accessibilityLabel={`Ghi chú ${stop.name}`} value={stop.note ?? ''} onChangeText={note => vm.updateStop(stop.id, { note })} multiline maxLength={500} placeholder="Ví dụ: đặt bàn trước, mua vé…" placeholderTextColor={c.muted} style={[s.input, { minHeight: 70, borderWidth: 0, borderRadius: 8 }]} />{trip.dayPlans.length > 1 && <View style={s.between}><Text style={s.small}>Chuyển sang ngày</Text><Pressable onPress={() => setMoveId(stop.id)} style={[s.input, s.row]}><Text style={s.text}>Ngày {day + 1}</Text><Icon name="chevron-down" size={16} color={c.ink} /></Pressable></View>}<View style={s.between}><View style={s.row}>{([-1, 1] as const).map(direction => <Pressable key={direction} accessibilityLabel={direction < 0 ? `Đưa ${stop.name} lên trước` : `Đưa ${stop.name} xuống sau`} disabled={direction < 0 ? index === 0 : index === stops.length - 1} onPress={() => onUpdate({ ...trip, dayPlans: reorderStop(trip.dayPlans, day, stop.id, direction) })} style={{ width: 44, height: 44, alignItems: 'center', justifyContent: 'center', opacity: (direction < 0 ? index === 0 : index === stops.length - 1) ? 0.3 : 1 }}><Icon name={direction < 0 ? 'arrow-up' : 'arrow-down'} size={16} /></Pressable>)}</View><Pressable onPress={() => remove(stop.id)} style={[s.row, { minHeight: 44 }]}><Icon name="trash-can-outline" size={16} color={c.red} /><Text style={{ color: c.red, fontSize: 12 }}>Xóa điểm dừng</Text></Pressable></View></View> : !!stop.note && <Text numberOfLines={2} style={s.small}>{stop.note}</Text>}
          </View>
        </View>)}
        {!!stops.length && <Pressable onPress={() => vm.setPicker(day)} style={[s.row, { minHeight: 48, borderRadius: 18, borderWidth: 1, borderStyle: 'dashed', borderColor: `${c.blue}66`, justifyContent: 'center' }]}><Icon name="plus" size={16} /><Text style={{ color: c.blue, fontSize: 14 }}>Thêm điểm dừng</Text></Pressable>}
        {!!trip.aiPreferences.length && <Text style={s.small}>Sở thích: {trip.aiPreferences.join(' · ')}</Text>}{!!(error || vm.message) && <Text style={s.error}>{error || vm.message}</Text>}
      </View>
    </ScrollView>
    <View style={[s.footer, { paddingVertical: 12 }]}><View style={[s.between, { marginBottom: 8 }]}><Text style={s.small}>{trip.dayPlans.length} ngày · {vm.stops.length} điểm dừng</Text><Text style={s.small}>{vm.stops.length ? 'Lịch trình của bạn' : 'Thêm địa điểm để lưu'}</Text></View><Button label="✓  Lưu chuyến đi" disabled={!vm.stops.length} onPress={vm.save} /></View>
    <Sheet visible={vm.picker !== null} title="Thêm địa điểm" onClose={() => vm.setPicker(null)}><Text style={s.small}>Ngày {day + 1} · {destination.name}</Text>{!!vm.message && <Text style={s.error}>{vm.message}</Text>}<PlacePicker selectedPlaces={trip.dayPlans.flatMap(plan => plan.stops)} savedPlaces={trip.dayPlans.flatMap(plan => plan.stops)} destination={destination} onPick={place => { try { const dayPlans = addStop(trip.dayPlans, day, place); onUpdate({ ...trip, dayPlans }); vm.setEdit(dayPlans[day].stops.at(-1)?.id ?? null); vm.setPicker(null); vm.setMessage(''); } catch (failure) { vm.setMessage(failure instanceof Error ? failure.message : 'Không thêm được địa điểm.'); } }} /></Sheet>
    <Sheet visible={!!moveId} title="Chuyển sang ngày" onClose={() => setMoveId(null)}>{trip.dayPlans.map((plan, index) => <Button key={plan.dayNumber} outline label={`Ngày ${index + 1}`} onPress={() => { if (moveId) onUpdate({ ...trip, dayPlans: moveStop(trip.dayPlans, day, index, moveId) }); setMoveId(null); vm.setEdit(null); }} />)}</Sheet>
  </KeyboardAvoidingView>;
}
