import { usePlacePickerViewModel } from './usePlacePickerViewModel';
import React from 'react';
import { ActivityIndicator, Image, Pressable, Text, TextInput, View } from 'react-native';
import { Place, TripDestination } from './tripModel';
import { Button, Icon, useTripUi } from './tripUi';
export default function PlacePicker({ destination, onPick, label = 'Địa danh, quán ăn, quán cà phê…', variant = 'place', savedPlaces = [], selectedPlaces = [] }: { destination: TripDestination; onPick: (place: Place) => void; label?: string; variant?: 'place' | 'hotel'; savedPlaces?: Place[]; selectedPlaces?: Place[] }) {
  const { c, s } = useTripUi();
  const { query, setQuery, results, busy, error } = usePlacePickerViewModel({ destination, onPick, label });
  const shown = query.trim().length >= 2 ? results : savedPlaces;
  const isSelected = (place: Place) => selectedPlaces.some(item => item.name.trim().toLocaleLowerCase() === place.name.trim().toLocaleLowerCase() || typeof item.lat === 'number' && typeof item.lng === 'number' && typeof place.lat === 'number' && typeof place.lng === 'number' && Math.abs(item.lat - place.lat) < 0.0005 && Math.abs(item.lng - place.lng) < 0.0005);
  return <View style={{ gap: 10 }}><View style={[s.row, { minHeight: 44, borderRadius: 24, paddingHorizontal: 12, backgroundColor: c.pale }]}><Icon name="magnify" color={c.muted} /><TextInput accessibilityLabel={label} value={query} onChangeText={setQuery} placeholder={label} placeholderTextColor={c.muted} style={[s.grow, { color: c.ink, fontSize: 14, minHeight: 36 }]} /></View>{busy && <ActivityIndicator color={c.blue} />}{!!error && <Text style={s.error}>{error}</Text>}{shown.map((place, index) => <Pressable key={`${place.id}-${index}`} accessibilityRole="button" accessibilityState={{ disabled: isSelected(place) }} disabled={isSelected(place)} onPress={() => onPick(place)} style={[s.row, { minHeight: 80, gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderColor: c.border }]}><View style={{ width: variant === 'hotel' ? 48 : 44, height: variant === 'hotel' ? 56 : 44, borderRadius: variant === 'hotel' ? 11 : 8, backgroundColor: variant === 'hotel' ? c.primaryLight : c.pale, alignItems: 'center', justifyContent: 'center' }}>{place.image && variant !== 'hotel' ? <Image source={{ uri: place.image }} style={{ width: 44, height: 44, borderRadius: 8 }} /> : <Icon name={variant === 'hotel' ? 'bed-outline' : 'map-marker-outline'} size={variant === 'hotel' ? 24 : 20} />}</View><View style={s.grow}><Text style={[s.title, { fontSize: variant === 'hotel' ? 16 : 17, fontWeight: variant === 'hotel' ? '600' : '400' }]}>{place.name}</Text><Text numberOfLines={2} style={s.small}>{place.note}</Text></View><Icon name={isSelected(place) ? "check" : "plus"} /></Pressable>)}{query.trim().length >= 2 && <Button outline label={`Dùng tên “${query.trim()}”`} onPress={() => onPick({ name: query.trim(), note: 'Địa điểm do bạn nhập, chưa có tọa độ' })} />}{!query && !savedPlaces.length && <Text style={s.small}>Nhập ít nhất 2 ký tự để tìm địa điểm.</Text>}</View>;
}
