import React, { useState } from 'react';
import { Image, Pressable, Text, View } from 'react-native';
import { Place } from './tripModel';
import { Icon, useTripUi } from './tripUi';
export default function PlaceDetailsContent({ place, city, onSave, onLocate, isSaved = false }: { place: Place; city: string; onSave?: () => void; onLocate: () => void; isSaved?: boolean }) {
  const { c, s } = useTripUi(); const [sourcesOpen, setSourcesOpen] = useState(false);
  const notes = place.communityNotes?.length ? place.communityNotes : [...(place.note ? [place.note] : []), 'Kiểm tra giờ mở cửa và giá vé trước khi ghé.', 'Dành thêm thời gian di chuyển nếu đi vào giờ cao điểm.'];
  return <View style={{ gap: 16 }}><View style={{ width: '100%', aspectRatio: 16 / 10, borderRadius: 18, backgroundColor: c.pale, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' }}>{place.image ? <Image source={{ uri: place.image }} style={{ width: '100%', height: '100%' }} /> : <Icon name="map-marker-outline" size={40} color={c.muted} />}</View>{place.rating !== undefined && <View style={s.row}><Icon name="star" size={15} color="#ff9500" /><Text style={s.text}>{place.rating}</Text>{place.reviewsCount !== undefined && <Text style={{ color: c.muted, fontSize: 14 }}>· {place.reviewsCount} đánh giá</Text>}</View>}
    <View style={{ gap: 8 }}><Text style={s.title}>Về địa điểm này</Text><Text style={{ color: c.muted, fontSize: 14, lineHeight: 22 }}>{place.description || place.note || `Một điểm ghé trong lịch trình tại ${city}. Thông tin chi tiết đang được cập nhật.`}</Text></View>
    <View style={{ borderWidth: 1, borderColor: c.border, borderRadius: 18, overflow: 'hidden' }}><View style={[s.row, { backgroundColor: '#ff95001a', paddingHorizontal: 16, paddingVertical: 12 }]}><Icon name="lightbulb-outline" size={17} color="#875000" /><Text style={{ color: c.ink, fontSize: 14, fontWeight: '600' }}>{place.communityNotes?.length ? 'Ghi chú cộng đồng' : 'Ghi chú tham khảo'}</Text></View><View style={{ padding: 16, gap: 8 }}>{notes.map((note, index) => <View key={index} style={[s.row, { alignItems: 'flex-start' }]}><Text style={{ color: c.muted }}>•</Text><Text style={[s.grow, { color: c.muted, fontSize: 14, lineHeight: 21 }]}>{note}</Text></View>)}</View></View>
    <Pressable onPress={() => setSourcesOpen(!sourcesOpen)} accessibilityState={{ expanded: sourcesOpen }} style={[s.between, { minHeight: 44 }]}><Text style={{ color: c.muted, fontSize: 14 }}>Nguồn thông tin</Text><Icon name={sourcesOpen ? 'chevron-up' : 'chevron-down'} size={17} color={c.muted} /></Pressable>{sourcesOpen && <Text style={{ color: c.muted, fontSize: 12, lineHeight: 18 }}>Thông tin từ danh mục địa điểm, tìm kiếm OpenStreetMap hoặc do bạn nhập. Ghi chú tham khảo không phải đánh giá đã xác minh từ cộng đồng.</Text>}
    {([{ icon: 'clock-outline', text: place.openingHours || 'Chưa cập nhật giờ mở cửa' }, { icon: 'map-marker-outline', text: place.address || place.city || city }, { icon: 'phone-outline', text: place.phone || 'Chưa cập nhật số điện thoại' }] as const).map(item => <View key={item.icon} style={[s.row, { paddingVertical: 12, borderBottomWidth: 1, borderColor: c.pale, alignItems: 'flex-start', gap: 12 }]}><Icon name={item.icon} size={18} color={c.muted} /><Text style={[s.grow, { fontSize: 14, color: c.muted }]}>{item.text}</Text></View>)}
    <View style={[s.row, { paddingVertical: 12, borderTopWidth: 1, borderColor: c.border, gap: 12 }]}>{onSave && <Pressable onPress={onSave} style={[s.button, s.row, { flex: 1, backgroundColor: c.pale }]}><Icon name={isSaved ? 'bookmark' : 'bookmark-outline'} size={17} /><Text style={{ color: c.blue, fontSize: 14, fontWeight: '600' }}>{isSaved ? 'Đã lưu' : 'Lưu địa điểm'}</Text></Pressable>}<Pressable onPress={onLocate} style={[s.button, s.row, { flex: 1 }]}><Icon name="navigation-variant-outline" color={c.onBlue} size={17} /><Text style={s.buttonText}>Chỉ đường</Text></Pressable></View>
  </View>;
}
