import React, { useState } from 'react';
import { Alert, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { addStop, addTripMember, displayDate, makeId, normalizeName, toggleStop, Trip, TripDestination, TripStop } from './tripModel';
import { Button, Icon, useTripUi } from './tripUi';
import { useTripPlanViewModel } from './useTripPlanViewModel';
import TripMap from './TripMap';
import PlacePicker from './PlacePicker';
import PlaceDetailsContent from './PlaceDetailsContent';
import PanelSheet from './PanelSheet';
import HotelSetupScreen from './HotelSetupScreen';
import TripUtilities from './TripUtilities';
import { Sheet } from '../chat/chatUi';
import { useToast } from '../theme/Toast';

const dayColors = ['#0066cc', '#34c759', '#ff9500', '#af52de', '#ff3b30'];
const categoryInfo = (category?: string) => ({ Nature: { icon: 'pine-tree', label: 'Thiên nhiên', color: '#28834a', background: '#e7f3e9' }, Food: { icon: 'silverware-fork-knife', label: 'Ẩm thực', color: '#b75b17', background: '#fff0df' }, Culture: { icon: 'bank-outline', label: 'Văn hóa', color: '#8061c7', background: '#f0eafa' }, Shopping: { icon: 'shopping-outline', label: 'Mua sắm', color: '#ba4684', background: '#f9eaf3' } }[category ?? ''] ?? { icon: 'map-marker-outline', label: 'Tham quan', color: '#0066cc', background: '#f0f6ff' });

export default function SamplePlanScreen({ trip, destination, companions = [], onBack, onUpdate, onSave, error, onSavePlace }: { trip: Trip; destination: TripDestination; companions?: Trip['members']; onBack: () => void; onUpdate: (trip: Trip) => void; onSave?: (trip: Trip) => void; error?: string; onSavePlace?: (place: TripStop) => void }) {
  const { c, s } = useTripUi();
  const toast = useToast();
  const vm = useTripPlanViewModel({ trip, destination, onBack, onUpdate, onSave, error });
  const [utility, setUtility] = useState<'expenses' | 'checklist' | null>(null);
  const [memberQuery, setMemberQuery] = useState('');
  const avatar = (member: Trip['members'][number]) => <View style={{ width: 32, height: 32, borderRadius: 16, backgroundColor: c.avatar, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }}>{member.avatar?.startsWith('http') ? <Image source={{ uri: member.avatar }} style={{ width: 32, height: 32 }} /> : <Text style={{ color: c.onBlue, fontSize: 11, fontWeight: '600' }}>{member.name.trim().split(/\s+/).slice(-2).map(part => part[0]).join('').toUpperCase()}</Text>}</View>;
  const photo = (stop: TripStop, height = 48) => <View style={{ width: 48, height, borderRadius: 8, overflow: 'hidden', backgroundColor: c.pale, alignItems: 'center', justifyContent: 'center' }}>{stop.image ? <Image source={{ uri: stop.image }} style={{ width: 48, height }} /> : <Icon name="map-marker-outline" color={c.muted} size={20} />}</View>;
  const locate = (stop: TripStop) => { if (typeof stop.lat !== 'number' || typeof stop.lng !== 'number') return Alert.alert('Chưa có tọa độ', 'Địa điểm này chưa có vị trí bản đồ.'); vm.setFocus(stop); vm.setSelected(null); };
  const remove = (id: string) => onUpdate({ ...trip, dayPlans: trip.dayPlans.map(day => ({ ...day, stops: day.stops.filter(stop => stop.id !== id) })) });
  if (vm.hotels) return <HotelSetupScreen destination={destination} days={trip.dayPlans.length} stays={trip.hotelStays ?? []} onChange={hotelStays => onUpdate({ ...trip, hotelStays })} onBack={() => vm.setHotels(false)} onDone={() => vm.setHotels(false)} />;
  const matches = companions.filter(member => !trip.members.some(item => item.id === member.id) && normalizeName(member.name).includes(normalizeName(memberQuery)));
  return <KeyboardAvoidingView style={{ flex: 1, backgroundColor: c.white }} behavior={Platform.OS === 'ios' ? 'padding' : 'height'} onLayout={event => vm.setHeight(event.nativeEvent.layout.height)}>
    <View style={{ height: vm.height * 0.35 }}><TripMap coords={trip.coords} stops={vm.shown} height={vm.height * 0.35} rounded={false} showLabel={false} focusedStop={vm.focus} onSelect={id => vm.setSelected(vm.stops.find(stop => stop.id === id) ?? null)} />
      <Pressable accessibilityLabel="Quay lại" onPress={onBack} style={[s.back, { position: 'absolute', top: 12, left: 12, width: 44, height: 44, backgroundColor: c.white }]}><Icon name="arrow-left" size={20} color={c.ink} /></Pressable>
      <Pressable accessibilityLabel="Lưu chuyến đi" disabled={!vm.stops.length} onPress={() => vm.saved ? toast('Đã lưu chuyến đi', 'Các thay đổi được giữ trong phiên hiện tại.') : vm.save()} style={{ position: 'absolute', top: 12, right: 12, minHeight: 44, borderRadius: 24, paddingHorizontal: 12, backgroundColor: c.white, flexDirection: 'row', alignItems: 'center', gap: 6, opacity: vm.stops.length ? 1 : 0.4 }}><Icon name="bookmark-plus-outline" size={20} /><Text style={{ color: c.blue, fontSize: 14, fontWeight: '600' }}>Lưu</Text></Pressable>
      <View style={{ position: 'absolute', top: 64, right: 12, flexDirection: 'row', gap: 8 }}>{([{ key: 'expenses', icon: 'currency-usd', label: 'Chi phí chuyến đi' }, { key: 'checklist', icon: 'checkbox-marked-outline', label: 'Danh sách chuẩn bị' }] as const).map(item => <Pressable key={item.key} accessibilityLabel={item.label} onPress={() => setUtility(item.key)} style={[s.back, { width: 44, height: 44, backgroundColor: c.white }]}><Icon name={item.icon} size={18} color={c.ink} /></Pressable>)}</View>
      {vm.focus && <View style={{ position: 'absolute', bottom: 20, left: 12, right: 12, backgroundColor: c.white, borderRadius: 11, paddingLeft: 12, flexDirection: 'row', alignItems: 'center', gap: 8 }}><Icon name="map-marker-outline" size={16} /><Text numberOfLines={1} style={[s.grow, { fontSize: 14, fontWeight: '600', color: c.ink }]}>{vm.focus.name}</Text><Pressable accessibilityLabel="Đóng vị trí đang xem" onPress={() => vm.setFocus(null)} style={{ width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }}><Icon name="close" size={16} color={c.muted} /></Pressable></View>}
    </View>
    <View style={{ flex: 1, borderTopLeftRadius: 18, borderTopRightRadius: 18, backgroundColor: c.white, overflow: 'hidden' }}><View style={{ width: 40, height: 4, borderRadius: 2, backgroundColor: c.border, alignSelf: 'center', marginVertical: 8 }} />
      <View style={[s.row, { paddingHorizontal: 16, paddingBottom: 8, gap: 12 }]}>{trip.image ? <Image source={{ uri: trip.image }} style={{ width: 48, height: 56, borderRadius: 8 }} /> : <View style={{ width: 48, height: 56, borderRadius: 8, backgroundColor: c.pale, alignItems: 'center', justifyContent: 'center' }}><Icon name="map-marker-outline" /></View>}<View style={s.grow}><Text style={[s.title, { fontSize: 16, lineHeight: 21 }]}>{trip.title}</Text><View style={[s.row, { marginTop: 4, flexWrap: 'wrap', gap: 12 }]}><Text style={s.small}>{trip.dayPlans.length} ngày · {vm.stops.length} địa điểm</Text><View style={s.row}><Icon name="creation" size={12} /><Text style={{ color: c.blue, fontSize: 12 }}>Lịch trình của bạn</Text></View></View></View></View>
      <Pressable accessibilityLabel="Quản lý bạn đồng hành" onPress={() => { setMemberQuery(''); vm.setMembers(true); }} style={[s.row, { marginHorizontal: 16, marginBottom: 8, minHeight: 44 }]}>{trip.members.length ? <View style={{ flexDirection: 'row' }}>{trip.members.slice(0, 3).map((member, index) => <View key={member.id} style={{ marginLeft: index ? -8 : 0, borderWidth: 2, borderColor: c.white, borderRadius: 18 }}>{avatar(member)}</View>)}</View> : <Icon name="account-group-outline" size={18} />}<View style={s.grow}><Text style={{ color: c.ink, fontSize: 12, fontWeight: '600' }}>{trip.members.length ? `${trip.members.length} bạn đồng hành` : 'Thêm bạn đồng hành'}</Text>{!!trip.members.length && <Text numberOfLines={1} style={s.small}>{trip.members.map(member => member.name).join(', ')}</Text>}</View><Icon name="account-plus-outline" size={18} /></Pressable>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ flexGrow: 0, borderBottomWidth: 1, borderColor: c.border }} contentContainerStyle={{ gap: 16, paddingHorizontal: 16 }}>{[{ id: -1, label: 'Tổng quan' }, ...trip.dayPlans.map((day, index) => ({ id: index, label: `Ngày ${day.dayNumber}` }))].map(item => <Pressable key={item.id} accessibilityRole="tab" accessibilityState={{ selected: vm.tab === item.id }} onPress={() => { vm.setTab(item.id); vm.setFocus(null); }} style={{ minHeight: 44, justifyContent: 'center', borderBottomWidth: 2, borderColor: vm.tab === item.id ? c.blue : 'transparent' }}><Text style={{ color: vm.tab === item.id ? c.ink : c.muted, fontSize: 14, fontWeight: '600' }}>{item.label}</Text></Pressable>)}</ScrollView>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 12, gap: 20 }}>
        {!!(error || vm.message) && <Text style={s.error}>{error || vm.message}</Text>}
        {vm.tab === -1 && !trip.hotelStays?.length && <View style={{ padding: 12, borderRadius: 11, borderWidth: 1, borderStyle: 'dashed', borderColor: c.border, backgroundColor: c.pale, marginTop: 12 }}><Text style={{ fontSize: 14, color: c.muted }}>Bạn chưa chọn khách sạn cho chuyến đi.</Text><Pressable onPress={() => vm.setHotels(true)} style={[s.row, { minHeight: 44, marginTop: 8 }]}><Icon name="plus" /><Text style={{ color: c.blue, fontSize: 14, fontWeight: '600' }}>Thêm khách sạn</Text></Pressable></View>}
        {trip.dayPlans.filter((_, index) => vm.tab === -1 || vm.tab === index).map(day => <View key={day.dayNumber} style={{ paddingTop: 12 }}>
          {(trip.hotelStays ?? []).filter(stay => stay.startDay === day.dayNumber).map(stay => <Pressable key={stay.id} onPress={() => vm.setHotels(true)} style={[s.row, { minHeight: 52, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 11, backgroundColor: c.pale, borderWidth: 1, borderColor: `${c.border}66`, marginBottom: 16, gap: 12 }]}><Icon name="bed-outline" size={21} color={c.hotel} /><Text numberOfLines={1} style={[s.text, s.grow]}>{stay.hotel.name}</Text><View style={[s.row, { borderRadius: 16, backgroundColor: c.white, paddingHorizontal: 8, paddingVertical: 4, gap: 4 }]}><Icon name="moon-waning-crescent" size={13} color={c.hotel} /><Text style={{ fontSize: 12, color: c.ink }}>{stay.endDay - stay.startDay} đêm</Text></View></Pressable>)}
          {vm.tab === -1 ? <><View style={[s.row, { marginBottom: 8 }]}><Text style={{ backgroundColor: dayColors[(day.dayNumber - 1) % dayColors.length], borderRadius: 12, paddingHorizontal: 8, paddingVertical: 4, color: c.onBlue, fontSize: 12, fontWeight: '600' }}>Ngày {day.dayNumber}</Text><Text numberOfLines={1} style={[s.grow, { fontSize: 14, fontWeight: '600', color: c.ink }]}>{destination.name}</Text><Text style={s.small}>{day.stops.length} địa điểm</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingBottom: 4 }}>{day.stops.map(stop => <Pressable key={stop.id} accessibilityLabel={`Xem ${stop.name} trong ngày ${day.dayNumber}`} onPress={() => vm.setSelected(stop)}>{photo(stop, 56)}</Pressable>)}</ScrollView></> : day.stops.map((stop, index) => { const category = categoryInfo(stop.category); return <View key={stop.id}><View style={[s.row, { paddingVertical: 8 }]}><Text style={{ width: 16, fontSize: 12, color: c.muted, textAlign: 'center' }}>{index + 1}</Text><Pressable accessibilityLabel={`Xem thông tin ${stop.name}`} onPress={() => vm.setSelected(stop)} style={[s.row, s.grow, { gap: 12 }]}>{photo(stop)}<View style={s.grow}><Text style={{ color: c.ink, fontSize: 14, lineHeight: 20, fontWeight: '600' }}>{stop.name}</Text><View style={[s.row, { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 16, backgroundColor: c.white === '#ffffff' ? category.background : c.primaryLight, marginTop: 4, gap: 4 }]}><Icon name={category.icon as React.ComponentProps<typeof Icon>['name']} size={12} color={c.white === '#ffffff' ? category.color : c.blue} /><Text style={{ fontSize: 12, color: c.white === '#ffffff' ? category.color : c.blue }}>{stop.categoryLabel || category.label}</Text></View></View></Pressable><Pressable accessibilityLabel={`Xóa ${stop.name} khỏi lịch trình`} onPress={() => remove(stop.id)} style={{ width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }}><Icon name="close" size={18} color={c.muted} /></Pressable></View><View style={[s.between, { marginLeft: 24, paddingBottom: 4 }]}><Text style={s.small}>{index === day.stops.length - 1 ? 'Điểm cuối trong ngày' : stop.time ? `Giờ đến: ${stop.time}` : 'Chưa có thông tin di chuyển'}</Text><Pressable accessibilityLabel={`Chỉ đường đến ${stop.name}`} onPress={() => locate(stop)} style={[s.row, { minHeight: 44, borderRadius: 24, backgroundColor: c.primaryLight, paddingHorizontal: 12, gap: 6 }]}><Icon name="navigation-variant-outline" size={14} /><Text style={{ fontSize: 12, color: c.blue, fontWeight: '600' }}>Chỉ đường</Text></Pressable></View></View>; })}
          {!day.stops.length && <Text style={{ color: c.muted, fontSize: 14 }}>Ngày tự do — thêm một địa điểm bạn muốn ghé.</Text>}
          <Pressable accessibilityLabel={`Thêm địa điểm vào ngày ${day.dayNumber}`} onPress={() => { vm.setMessage(''); vm.setPicker(day.dayNumber - 1); }} style={[s.row, { minHeight: 44, marginTop: 8, paddingHorizontal: 8 }]}><Icon name="plus" /><Text style={{ color: c.blue, fontSize: 14 }}>Thêm địa điểm</Text></Pressable>
        </View>)}
        <View style={s.row}><Icon name="calendar-month-outline" size={14} color={c.muted} /><Text style={s.small}>{trip.dateMode === 'flexible' ? 'Ngày khởi hành linh hoạt' : `${displayDate(trip.startDate)} – ${displayDate(trip.endDate)}`}</Text></View>
      </ScrollView>
      <PanelSheet visible={!!vm.selected} title={vm.selected?.name ?? 'Chi tiết địa điểm'} onClose={() => vm.setSelected(null)}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 16 }}>{vm.selected && <><PlaceDetailsContent place={vm.selected} city={destination.name} onSave={onSavePlace ? () => onSavePlace(vm.selected!) : undefined} onLocate={() => locate(vm.selected!)} />{vm.saved && <Button outline label={vm.selected.status === 'completed' ? 'Đã đến · mở lại' : vm.selected.status === 'active' ? 'Đang đi · hoàn thành' : 'Bắt đầu đi'} onPress={() => { onUpdate(toggleStop(trip, vm.selected!.id)); vm.setSelected(null); }} />}</>}</ScrollView></PanelSheet>
      <PanelSheet visible={vm.picker !== null} height="78%" title="Thêm địa điểm" onClose={() => vm.setPicker(null)}><Text style={s.small}>Ngày {(vm.picker ?? 0) + 1} · {destination.name}</Text><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ paddingTop: 16 }}>{!!vm.message && <Text style={s.error}>{vm.message}</Text>}<PlacePicker selectedPlaces={trip.dayPlans.flatMap(plan => plan.stops)} savedPlaces={trip.dayPlans.flatMap(plan => plan.stops)} destination={destination} onPick={place => { if (vm.picker === null) return; try { onUpdate({ ...trip, dayPlans: addStop(trip.dayPlans, vm.picker, place) }); vm.setPicker(null); } catch (failure) { vm.setMessage(failure instanceof Error ? failure.message : 'Không thêm được địa điểm.'); } }} /></ScrollView></PanelSheet>
    </View>
    <Sheet visible={!!utility} title={utility === 'checklist' ? 'Danh sách chuẩn bị' : 'Chi phí chuyến đi'} onClose={() => setUtility(null)}>{utility && <View style={{ height: vm.height * 0.65 }}><TripUtilities key={utility} initialTab={utility} hideTabs trip={trip} onBack={() => setUtility(null)} onUpdate={onUpdate} /></View>}</Sheet>
    <Sheet visible={vm.members} title="Bạn đồng hành" onClose={() => vm.setMembers(false)}><Text style={[s.title, { fontSize: 14 }]}>Người tham gia · {trip.members.length}</Text>{trip.members.length ? trip.members.map(member => <View key={member.id} style={[s.row, { minHeight: 56, borderBottomWidth: 1, borderColor: c.border, gap: 12 }]}>{avatar(member)}<Text style={[s.text, s.grow]}>{member.name}</Text><Pressable accessibilityLabel={`Xóa ${member.name} khỏi chuyến đi`} onPress={() => onUpdate({ ...trip, members: trip.members.filter(item => item.id !== member.id) })} style={{ width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }}><Icon name="close" color={c.muted} /></Pressable></View>) : <Text style={{ color: c.muted, fontSize: 14 }}>Chưa có bạn đồng hành.</Text>}<Text style={[s.title, { fontSize: 14 }]}>Thêm người tham gia</Text><View style={[s.row, s.input, { borderRadius: 24, borderWidth: 0 }]}><Icon name="magnify" size={16} color={c.muted} /><TextInput accessibilityLabel="Tìm hoặc nhập tên bạn đồng hành" placeholder="Nhập tên bạn đồng hành" placeholderTextColor={c.muted} value={memberQuery} onChangeText={setMemberQuery} maxLength={80} style={{ flex: 1, color: c.ink, fontSize: 16, minHeight: 44 }} /></View>{matches.map(member => <Pressable key={member.id} onPress={() => onUpdate(addTripMember(trip, member))} style={[s.row, { minHeight: 64, borderBottomWidth: 1, borderColor: c.border }]}>{avatar(member)}<Text style={[s.text, s.grow]}>{member.name}</Text><Icon name="plus" /></Pressable>)}{memberQuery.trim().length >= 2 && ![...trip.members, ...matches].some(member => normalizeName(member.name) === normalizeName(memberQuery)) && <Pressable onPress={() => { onUpdate(addTripMember(trip, { id: makeId(), name: memberQuery.trim() })); setMemberQuery(''); }} style={[s.row, { minHeight: 44 }]}><Icon name="plus" /><Text style={{ color: c.blue, fontSize: 14 }}>Thêm “{memberQuery.trim()}”</Text></Pressable>}<Text style={s.small}>Danh sách được giữ trong chuyến đi của phiên hiện tại. Chưa gửi lời mời thực tế.</Text></Sheet>
  </KeyboardAvoidingView>;
}
