import { MaterialCommunityIcons } from '@expo/vector-icons';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

export const c = { blue: '#0066cc', ink: '#1d1d1f', muted: '#7a7a7a', border: '#e0e0e0', pale: '#f5f5f7', white: '#ffffff', green: '#34c759', red: '#ff3b30' };
export function Icon({ name, size = 18, color = c.blue }: { name: keyof typeof MaterialCommunityIcons.glyphMap; size?: number; color?: string }) {
  return <MaterialCommunityIcons name={name} size={size} color={color} />;
}
export function Button({ label, onPress, outline = false, disabled = false }: { label: string; onPress: () => void; outline?: boolean; disabled?: boolean }) {
  return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [s.button, outline && s.outline, (pressed || disabled) && { opacity: 0.6 }]}><Text style={[s.buttonText, outline && { color: c.blue }]}>{label}</Text></Pressable>;
}
export function Header({ title, subtitle, onBack, action }: { title: string; subtitle?: string; onBack: () => void; action?: React.ReactNode }) {
  return <View style={s.header}><Pressable accessibilityLabel="Quay lại" accessibilityRole="button" onPress={onBack} hitSlop={8} style={s.back}><Icon name="arrow-left" size={18} color={c.ink} /></Pressable><View style={s.grow}><Text numberOfLines={1} style={[s.title, { textAlign: 'center' }]}>{title}</Text>{subtitle && <Text numberOfLines={1} style={[s.small, { textAlign: 'center' }]}>{subtitle}</Text>}</View>{action ?? <View style={{ width: 32 }} />}</View>;
}
export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: c.pale }, grow: { flex: 1, minWidth: 0 }, header: { minHeight: 57, paddingHorizontal: 16, paddingVertical: 12, backgroundColor: c.white, borderBottomWidth: 1, borderColor: c.border, flexDirection: 'row', alignItems: 'center', gap: 8 }, back: { width: 32, height: 32, borderRadius: 20, borderWidth: 1, borderColor: c.border, alignItems: 'center', justifyContent: 'center' }, body: { padding: 16, gap: 14, paddingBottom: 24 }, card: { backgroundColor: c.white, borderWidth: 1, borderColor: c.border, borderRadius: 16, padding: 16, gap: 10 }, row: { flexDirection: 'row', alignItems: 'center', gap: 8 }, between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, title: { fontSize: 14, color: c.ink, fontWeight: '600' }, text: { fontSize: 12, color: c.ink }, small: { fontSize: 11, color: c.muted }, label: { fontSize: 10, color: c.muted, fontWeight: '600' }, link: { color: c.blue, fontSize: 11, fontWeight: '600' }, input: { minHeight: 38, borderRadius: 12, borderWidth: 1, borderColor: c.border, backgroundColor: c.pale, paddingHorizontal: 12, paddingVertical: 8, fontSize: 12, color: c.ink }, button: { minHeight: 40, backgroundColor: c.blue, borderRadius: 25, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 }, buttonText: { fontSize: 12, fontWeight: '600', color: c.white }, outline: { borderWidth: 1, borderColor: c.blue, backgroundColor: c.white }, badge: { backgroundColor: c.pale, borderWidth: 1, borderColor: c.border, borderRadius: 20, paddingHorizontal: 8, paddingVertical: 3, color: c.blue, fontSize: 10 }, divider: { borderTopWidth: 1, borderColor: '#f0f0f0', paddingTop: 8 }, chip: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1, borderColor: c.border, backgroundColor: c.pale }, selected: { backgroundColor: '#eef6fe', borderColor: c.blue }, error: { fontSize: 12, color: c.red }, footer: { padding: 16, backgroundColor: c.white, borderTopWidth: 1, borderColor: c.border },
});
