import React from 'react';
import { Modal, Pressable, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Icon, useTripUi } from './trips/tripUi';
import { useReducedMotion } from './theme/useReducedMotion';
export default function CreateMenu({ visible, onClose, onTrip, onList, onPlace }: { visible: boolean; onClose: () => void; onTrip: () => void; onList: () => void; onPlace: () => void }) {
  const { c } = useTripUi(); const reducedMotion = useReducedMotion(); const insets = useSafeAreaInsets();
  return <Modal visible={visible} transparent animationType={reducedMotion ? 'none' : 'fade'} onRequestClose={onClose}><View style={{ flex: 1, backgroundColor: '#00000040', justifyContent: 'flex-end', paddingHorizontal: 16, paddingBottom: 32 + insets.bottom }}><Pressable accessibilityLabel="Đóng menu tạo mới" onPress={onClose} style={{ position: 'absolute', inset: 0 }} /><View accessibilityViewIsModal style={{ width: '100%', maxWidth: 420, alignSelf: 'center' }}><View style={{ padding: 8, borderRadius: 18, backgroundColor: c.pale, gap: 8 }}>{([{ title: 'Tạo chuyến đi mới', description: 'Lên kế hoạch cho hành trình tiếp theo', icon: 'bag-suitcase-outline', action: onTrip }, { title: 'Tạo danh sách mới', description: 'Gom những địa điểm yêu thích của bạn', icon: 'playlist-plus', action: onList }, { title: 'Thêm địa điểm', description: 'Lưu những nơi bạn muốn khám phá', icon: 'map-marker-outline', action: onPlace }] as const).map(item => <Pressable key={item.title} onPress={item.action} style={({ pressed }) => [{ minHeight: 80, backgroundColor: c.white, borderRadius: 11, padding: 16, flexDirection: 'row', gap: 12, alignItems: 'center' }, pressed && { opacity: 0.88, transform: [{ scale: 0.98 }] }]}><Icon name={item.icon} size={28} /><View style={{ flex: 1 }}><Text style={{ color: c.ink, fontSize: 17, fontWeight: '600' }}>{item.title}</Text><Text style={{ color: c.muted, fontSize: 12, lineHeight: 17, marginTop: 4 }}>{item.description}</Text></View><Icon name="chevron-right" size={16} color={c.muted} /></Pressable>)}</View><Pressable onPress={onClose} accessibilityLabel="Đóng menu tạo mới" style={{ width: 44, height: 44, borderRadius: 22, backgroundColor: '#1d1d1f', alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginTop: 16 }}><Icon name="close" size={24} color={c.onBlue} /></Pressable></View></View></Modal>;
}
