import React, { useEffect } from 'react';
import { Alert, BackHandler, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { Header, Icon, useTripUi } from './trips/tripUi';
export default function EditProfileScreen({ user, onBack }: { user: { displayName: string; email: string }; onBack: () => void }) {
  const { c, s } = useTripUi();
  useEffect(() => { const sub = BackHandler.addEventListener('hardwareBackPress', () => { onBack(); return true; }); return () => sub.remove(); }, [onBack]);
  const unavailable = () => Alert.alert('Chưa hỗ trợ cập nhật hồ sơ', 'Thông tin đang lấy từ tài khoản đã đăng nhập. Dịch vụ cập nhật hồ sơ chưa được kết nối.');
  return <View style={s.screen}><Header title="Chỉnh sửa hồ sơ" onBack={onBack} /><ScrollView contentContainerStyle={s.body}><View style={[s.card, { alignItems: 'center', padding: 20, gap: 12 }]}><Pressable accessibilityLabel="Thay ảnh đại diện" onPress={unavailable} style={{ width: 80, height: 80, borderRadius: 40, backgroundColor: c.blue, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: c.onBlue, fontSize: 24, fontWeight: '600' }}>{user.displayName.trim().slice(-1).toUpperCase()}</Text><View style={{ position: 'absolute', bottom: -4, right: -4, width: 32, height: 32, borderRadius: 16, borderWidth: 1, borderColor: c.border, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center' }}><Icon name="camera-outline" size={16} /></View></Pressable><Pressable onPress={unavailable} style={{ minHeight: 44, justifyContent: 'center' }}><Text style={s.link}>Thay ảnh đại diện</Text></Pressable></View><View style={[s.card, { gap: 16 }]}><Text style={[s.title, { fontSize: 14 }]}>Tên hiển thị</Text><TextInput accessibilityLabel="Tên hiển thị" value={user.displayName} editable={false} style={[s.input, { fontSize: 16, borderWidth: 0, borderRadius: 8 }]} /><Text style={[s.title, { fontSize: 14 }]}>Email</Text><TextInput accessibilityLabel="Email" value={user.email} editable={false} style={[s.input, { fontSize: 16, borderWidth: 0, borderRadius: 8 }]} /></View><Text style={s.small}>Cập nhật hồ sơ hiện chưa khả dụng.</Text><Pressable onPress={unavailable} style={s.button}><Text style={s.buttonText}>Lưu thay đổi</Text></Pressable></ScrollView></View>;
}
